"""hash column on timeseries

Revision ID: 104051a1ed56
Revises: 81f81a4ff543
Create Date: 2018-04-27 13:40:15.572047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '104051a1ed56'
down_revision = '81f81a4ff543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('timeseriesdata2')
    op.add_column('timeseries', sa.Column('data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timeseries', 'timeseriesdata', ['data_id'], ['id'])
    op.add_column('timeseriesdata', sa.Column('values', sa.ARRAY(sa.Numeric()), nullable=True))
    op.drop_column('timeseriesdata', 'sample')
    op.drop_column('timeseriesdata', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseriesdata', sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('timeseriesdata', sa.Column('sample', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('timeseriesdata', 'values')
    op.drop_constraint(None, 'timeseries', type_='foreignkey')
    op.drop_column('timeseries', 'data_id')
    op.create_table('timeseriesdata2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timeseries_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('values', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], name='timeseriesdata2_timeseries_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='timeseriesdata2_pkey')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    # ### end Alembic commands ###
