"""Added channels

Revision ID: 1abc2b533e5a
Revises: 466b2e556afa
Create Date: 2018-04-19 08:49:54.976924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1abc2b533e5a'
down_revision = '466b2e556afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('channel_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'channel_no', name='stepchannel_pk')
    )
    op.drop_table('sessions')
    op.add_column('timeseries', sa.Column('step_channel_id', sa.Integer(), nullable=True))
    op.drop_constraint('timeseries_step_id_fkey', 'timeseries', type_='foreignkey')
    op.create_foreign_key(None, 'timeseries', 'step_channel', ['step_channel_id'], ['id'])
    op.drop_column('timeseries', 'step_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('step_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timeseries', type_='foreignkey')
    op.create_foreign_key('timeseries_step_id_fkey', 'timeseries', 'steps', ['step_id'], ['id'])
    op.drop_column('timeseries', 'step_channel_id')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('step_channel')
    # ### end Alembic commands ###
