"""hash column on timeseries

Revision ID: 377321ac58ec
Revises: 0bfc5ad24e46
Create Date: 2018-04-27 14:06:16.796569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377321ac58ec'
down_revision = '0bfc5ad24e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeseries_timeseriesdata',
    sa.Column('timeseries_id', sa.Integer(), nullable=True),
    sa.Column('timeseriesdata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], ),
    sa.ForeignKeyConstraint(['timeseriesdata_id'], ['timeseriesdata.id'], )
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('timeseries_timeseriesdata')
    # ### end Alembic commands ###
