"""Added reports table

Revision ID: 466b2e556afa
Revises: 217ab5a5d9b0
Create Date: 2018-04-18 10:33:25.797729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '466b2e556afa'
down_revision = '217ab5a5d9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('information', sa.UnicodeText(), nullable=True),
    sa.Column('erg_da001_re', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_da001_le', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_da3_re', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_da3_le', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_da3op_re', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_da3op_le', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_la3_re', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_la3_le', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_flicker_re', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_flicker_le', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_phnr_re', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_phnr_le', sa.Unicode(length=80), nullable=True),
    sa.Column('erg_comment', sa.UnicodeText(), nullable=True),
    sa.Column('mferg_comment', sa.UnicodeText(), nullable=True),
    sa.Column('perg_comment', sa.UnicodeText(), nullable=True),
    sa.Column('fvep_comment', sa.UnicodeText(), nullable=True),
    sa.Column('pvep_comment', sa.UnicodeText(), nullable=True),
    sa.Column('overview_comment', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('reports')
    # ### end Alembic commands ###
