"""hash column on timeseries

Revision ID: 5c2f81be19a6
Revises: 104051a1ed56
Create Date: 2018-04-27 13:43:10.752984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c2f81be19a6'
down_revision = '104051a1ed56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_constraint('timeseriesdata_timeseries_id_fkey', 'timeseriesdata', type_='foreignkey')
    op.drop_column('timeseriesdata', 'timeseries_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseriesdata', sa.Column('timeseries_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('timeseriesdata_timeseries_id_fkey', 'timeseriesdata', 'timeseries', ['timeseries_id'], ['id'])
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    # ### end Alembic commands ###
