"""Added channels

Revision ID: 7752d671584f
Revises: 1abc2b533e5a
Create Date: 2018-04-19 09:25:36.703338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7752d671584f'
down_revision = '1abc2b533e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_no', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['step_channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'result_no', name='results_pk')
    )
    op.drop_table('sessions')
    op.add_column('timeseries', sa.Column('result_id', sa.Integer(), nullable=True))
    op.drop_constraint('timeseries_step_channel_id_fkey', 'timeseries', type_='foreignkey')
    op.create_foreign_key(None, 'timeseries', 'results', ['result_id'], ['id'])
    op.drop_column('timeseries', 'step_channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('step_channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'timeseries', type_='foreignkey')
    op.create_foreign_key('timeseries_step_channel_id_fkey', 'timeseries', 'step_channel', ['step_channel_id'], ['id'])
    op.drop_column('timeseries', 'result_id')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('results')
    # ### end Alembic commands ###
