"""Added test type classes

Revision ID: 8ca4130864cd
Revises: fdab76f83861
Create Date: 2018-01-12 15:50:28.691184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ca4130864cd'
down_revision = 'fdab76f83861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    test_types = postgresql.ENUM('mferg', 'vep', 'perg', 'eog', name='test_class')
    test_types.create(op.get_bind())
    op.add_column('test_types', sa.Column('test_class', sa.Enum('mferg', 'vep', 'perg', 'eog', name='test_class'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_types', 'test_class')
    test_types = postgresql.ENUM('mferg', 'vep', 'perg', 'eog', name='test_class')
    test_types.drop(op.get_bind())
    # ### end Alembic commands ###
