"""hash column on timeseries

Revision ID: 8f461c9ac098
Revises: fb8cdcd11673
Create Date: 2018-04-27 13:38:10.425632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f461c9ac098'
down_revision = 'fb8cdcd11673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('marker_type', sa.Enum('time', 'amplitude', name='marker_type'), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('normal_min', sa.Numeric(), nullable=True),
    sa.Column('normal_max', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sessions')
    op.add_column('timeseriesdata', sa.Column('hash_str', sa.Unicode(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeseriesdata', 'hash_str')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('markers')
    # ### end Alembic commands ###
