"""Remote test_types table

Revision ID: 93aad2a2c7b9
Revises: be09e00f2f5e
Create Date: 2018-02-01 15:11:08.074801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93aad2a2c7b9'
down_revision = 'be09e00f2f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('test_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('abbrv_name', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('test_class', postgresql.ENUM('mferg', 'vep', 'perg', 'eog', name='test_class'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_types_pkey')
    )
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    # ### end Alembic commands ###
