"""modified markers

Revision ID: b14b2bbc524c
Revises: ad590527782a
Create Date: 2018-04-27 17:14:33.913484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b14b2bbc524c'
down_revision = 'ad590527782a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.add_column('markers', sa.Column('amp', sa.Numeric(), nullable=False))
    op.add_column('markers', sa.Column('amp_normal_max', sa.Numeric(), nullable=True))
    op.add_column('markers', sa.Column('amp_normal_min', sa.Numeric(), nullable=True))
    op.add_column('markers', sa.Column('it', sa.Numeric(), nullable=False))
    op.add_column('markers', sa.Column('it_normal_max', sa.Numeric(), nullable=True))
    op.add_column('markers', sa.Column('it_normal_min', sa.Numeric(), nullable=True))
    op.drop_column('markers', 'normal_min')
    op.drop_column('markers', 'marker_type')
    op.drop_column('markers', 'value')
    op.drop_column('markers', 'normal_max')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('normal_max', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('markers', sa.Column('marker_type', postgresql.ENUM('time', 'amplitude', name='marker_type'), autoincrement=False, nullable=True))
    op.add_column('markers', sa.Column('normal_min', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('markers', 'it_normal_min')
    op.drop_column('markers', 'it_normal_max')
    op.drop_column('markers', 'it')
    op.drop_column('markers', 'amp_normal_min')
    op.drop_column('markers', 'amp_normal_max')
    op.drop_column('markers', 'amp')
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    # ### end Alembic commands ###
