"""Added timeseresdata as array

Revision ID: b92ecccb5e39
Revises: 7752d671584f
Create Date: 2018-04-19 14:54:06.868981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b92ecccb5e39'
down_revision = '7752d671584f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeseriesdata2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeseries_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['timeseries_id'], ['timeseries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sessions')
    op.alter_column('step_channel', 'channel_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('step_channel', 'channel_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('session_id', name='sessions_session_id_key')
    )
    op.drop_table('timeseriesdata2')
    # ### end Alembic commands ###
